### ISSUE TITLE
非常感谢你的分享、对我帮助很大

### ISSUE THREAD

**Issue by STRIVING-NICE** [akjayant/Image-Captioning-via-YOLOv5-EncoderDecoderwithAttention#1]

**Comment by akjayant** [comment]
I can't understand Chinese, can you please write it in English? 
Translators says "it helped you a lot". Is it correct?

**Comment by STRIVING-NICE** [comment]
> I can't understand Chinese, can you please write it in English?
> Translators says "it helped you a lot". Is it correct?

Yes, thank you very much for sharing

**Comment by akjayant** [comment]
You are welcome.
